#!/usr/bin/env python
"""Generate a categorized env-var classification doc.

Produces docs/ENV_VARS_CLASSIFICATION.md from docs/env_dict.md.

Why this exists
---------------
The repository already maintains a flat allowlist of env vars in docs/env_dict.md.
For roadmap work (configuration unification), it is useful to also have:
- A stable category per variable (metrics, collectors, storage, etc.)
- A lifecycle status for a curated subset (from src.config.env_lifecycle)
- A clear statement about reload scope

Scope semantics
---------------
Today, EnvConfig caches parsed env values and production code does not
periodically clear that cache. As a result, almost all env vars behave as
"startup-only" (restart required to apply changes).

We still emit a "scope" column so future work can explicitly mark the few
variables that are intentionally reloaded at runtime.

This script is intentionally best-effort and non-strict.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[2]
DOCS_ENV_DICT = ROOT / "docs" / "env_dict.md"
OUT = ROOT / "docs" / "ENV_VARS_CLASSIFICATION.md"


@dataclass(frozen=True)
class Lifecycle:
    name: str
    status: str
    introduced: str | None = None
    deprecated: str | None = None
    removal_target: str | None = None
    replacement: str | None = None


def _load_lifecycle() -> dict[str, Lifecycle]:
    try:
        from src.config.env_lifecycle import ENV_LIFECYCLE_REGISTRY  # type: ignore

        out: dict[str, Lifecycle] = {}
        for e in ENV_LIFECYCLE_REGISTRY:
            out[e.name] = Lifecycle(
                name=e.name,
                status=str(getattr(e, "status", "")) or "unknown",
                introduced=getattr(e, "introduced", None),
                deprecated=getattr(e, "deprecated", None),
                removal_target=getattr(e, "removal_target", None),
                replacement=getattr(e, "replacement", None),
            )
        return out
    except Exception:
        return {}


def _iter_env_names(doc_text: str) -> tuple[list[str], list[str]]:
    """Return (names, prefixes).

    docs/env_dict.md contains one token per line at the top-level like:
      G6_FOO_BAR: documented
      G6_SOME_PREFIX_: documented
    """
    names: list[str] = []
    prefixes: list[str] = []
    for raw in doc_text.splitlines():
        line = raw.strip()
        if not line.startswith("G6_"):
            continue
        token = line.split(":", 1)[0].strip()
        if not token:
            continue
        if token.endswith("_"):
            prefixes.append(token)
        else:
            names.append(token)
    # Make stable
    names = sorted(set(names))
    prefixes = sorted(set(prefixes))
    return names, prefixes


def _category_for(name: str) -> str:
    # Order matters: more specific first.
    if name.startswith("G6_ADAPTIVE_"):
        return "adaptive"
    if name.startswith("G6_ALERTS_") or name.startswith("G6_ALERT_"):
        return "alerts"
    if name.startswith("G6_METRICS_"):
        return "metrics"
    if name.startswith("G6_PANELS_"):
        return "panels"
    if name.startswith("G6_DASHBOARD_") or name.startswith("G6_WEB_"):
        return "web"
    if name.startswith("G6_SHADOW_") or name.startswith("G6_PARITY_"):
        return "parity"
    if name.startswith("G6_PROVIDER_") or name.startswith("G6_KITE_") or name.startswith("G6_USE_"):
        return "providers"
    if name.startswith("G6_CSV_") or name.startswith("G6_STORAGE_") or name.startswith("G6_PARQUET_"):
        return "storage"
    if name.startswith("G6_LOOP_") or name.startswith("G6_BOOTSTRAP_") or name.startswith("G6_ORCH"):
        return "orchestrator"
    if name.startswith("G6_EVENTS_"):
        return "events"
    return "core"


def _scope_for(_name: str) -> str:
    # Conservative default: EnvConfig caches and production code doesn't clear cache.
    return "startup (restart)"


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def build_markdown(names: Iterable[str], prefixes: Iterable[str], lifecycle: dict[str, Lifecycle]) -> str:
    out: list[str] = []
    out.append("# G6 Environment Variable Classification")
    out.append("")
    out.append("This file is generated by `scripts/docs/gen_env_classification.py`.")
    out.append("")
    out.append("## Reload Semantics")
    out.append("")
    out.append(
        "Env access is centralized via `src.config.env_config.EnvConfig`, which caches parsed values. "
        "Because production code does not periodically call `EnvConfig.clear_cache()`, environment "
        "variables behave as *startup-only* in practice (restart required to apply changes)."
    )
    out.append("")
    out.append("## Variables")
    out.append("")
    out.append("Name | Category | Scope | Lifecycle | Replacement | Notes")
    out.append("--- | --- | --- | --- | --- | ---")

    for name in sorted(set(names)):
        cat = _category_for(name)
        scope = _scope_for(name)
        lc = lifecycle.get(name)
        lifecycle_status = lc.status if lc else "documented"
        replacement = lc.replacement if lc and lc.replacement else ""
        notes = ""
        if lc:
            bits: list[str] = []
            if lc.introduced:
                bits.append(f"introduced={lc.introduced}")
            if lc.deprecated:
                bits.append(f"deprecated={lc.deprecated}")
            if lc.removal_target:
                bits.append(f"removal_target={lc.removal_target}")
            notes = ", ".join(bits)

        out.append(
            f"{_md_escape(name)} | {_md_escape(cat)} | {_md_escape(scope)} | {_md_escape(lifecycle_status)} | {_md_escape(replacement)} | {_md_escape(notes)}"
        )

    px = sorted(set(prefixes))
    if px:
        out.append("")
        out.append("## Prefix Allowlist")
        out.append("")
        out.append(
            "These entries represent documented *prefixes* (any env var starting with the prefix is considered allowed/documented)."
        )
        out.append("")
        for p in px:
            out.append(f"- {p}")

    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if not DOCS_ENV_DICT.exists():
        print(f"Missing {DOCS_ENV_DICT}", file=sys.stderr)
        return 2

    text = DOCS_ENV_DICT.read_text(encoding="utf-8", errors="ignore")
    names, prefixes = _iter_env_names(text)
    lc = _load_lifecycle()

    md = build_markdown(names, prefixes, lc)
    OUT.write_text(md, encoding="utf-8")
    print(f"Wrote: {OUT}")
    print(f"Vars: {len(names)}  Prefixes: {len(prefixes)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
