apiVersion: 1

datasources:
  - name: G6 JSON API
    uid: jsonapi
    type: simpod-json-datasource
    url: http://localhost:9500
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      timeout: 60
      tlsSkipVerify: true
